defaults: &defaults
  docker:
    - image: circleci/node:10.15.3-browsers
  working_directory: ~/project/rieau-ui

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # default if no checksum found
          - v1-dependencies-
      - run: npm ci
      - save_cache:
          root: '~'
          paths:
            - .cache
            - .npm
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: '~'
          paths:
            - .cache
            - .npm
            - project/rieau-ui
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: '~'
      - run: cp .env.sample .env
      - run: 
          environment: 
            - REACT_APP_BASENAME: /rieau-ui
            - PUBLIC_URL: https://mtes-mct.github.io/rieau-ui
            - REACT_APP_PUBLIC_URL: https://mtes-mct.github.io/rieau-ui
          command: npm run build:dev
      - persist_to_workspace:
          root: .
          paths:
            - build
  check-vulnerabilities:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: '~'
      - run: npm audit
  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: '~'
      - run: npm run test:unit
  e2e-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: '~'
      - run: npm run test:e2e
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: '~'
      - run: 
          command: npm run lint
  deploy-github:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: '~'
      - run: cp .env.sample .env
      - run: 
          environment:
            REACT_APP_API_MOCK: true
            REACT_APP_BASENAME: /rieau-ui
            PUBLIC_URL: https://mtes-mct.github.io/rieau-ui
            REACT_APP_PUBLIC_URL: https://mtes-mct.github.io/rieau-ui
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "<circleci>"
            git config user.name "CircleCi"
            npm run deploy:dev

workflows:
  version: 2
  weekly-dependency-check:
    triggers:
      - schedule:
          cron: "0 0 * * 0" # every sunday at midnight
          filters:
            branches:
              only:
                - master
    jobs:
      - prepare:
          requires: []
      - check-vulnerabilities:
          requires:
            - prepare
  build_accept_deploy:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - build:
          requires:
            - lint
      - unit-tests:
          requires:
            - build
      - e2e-tests:
          requires:
            - unit-tests
      - deploy-github:
          requires:
            - e2e-tests
          filters:
            branches:
              only:
                - master
